### ISSUE TITLE
callback do not being invoked

### ISSUE THREAD

**Issue by nkuhero** [stellar/bridge-server#104]
I  set  receive in bridge.cfg
but  it does not work.

#bridge.cfg
[callbacks]
receive = "http://127.0.0.1:8002/receive"

I  start up a service  listen in 8002
but  it  is not being invoked

**Comment by bartekn** [comment]
This is likely issue on your side because we know of many projects that use bridge server in the latest version without any problems. Please ask for help at [Stellar Stack Exchange](https://stellar.stackexchange.com/).
