### ISSUE TITLE
A way to let the API user know about errors

### ISSUE THREAD

**Issue by ramontayag** [stellar/bridge-server#107]
Does the stellar auth protocol have a way to report errors? For example, maybe the sender’s domain does not have a Stellar TOML and instead of having the `error` status, we can report exactly what’s wrong.

If there's none, I can propose just adding a new field, like:

```json
{
    "info_status": "ok",
    "tx_status": "error",
    "tx_status_msg": "Sender does not have Stellar TOML in the domain",
}
```

**Comment by bartekn** [comment]
Yes, it's defined in [SEP-0003](https://github.com/stellar/stellar-protocol/blob/master/ecosystem/sep-0003.md), example:
```
{
    "info_status": "ok",
    "tx_status": "error",
    "error": "Invalid country code."
}
```

It seems that [Compliance protocol](https://www.stellar.org/developers/guides/compliance-protocol.html) doc in the Dev portal is out of date. Will create an issue to update it.

**Comment by ramontayag** [comment]
Ah yes was looking at the protocol doc. Thanks!
