### ISSUE TITLE
'missing_parameter' while connecting bridge server

### ISSUE THREAD

**Issue by MorePravin** [stellar/bridge-server#108]
Hi, 
I am facing one issue while connecting to bridge server.

My issue is like ;
I am trying to send payment using bridge server which is installed locally with version "bridge-v0.0.30-linux-amd64".
And uses same program and bridge.cfg file from "https://www.stellar.org/developers/guides/anchor/2-bridge-server.html". 
But while running Java program I got following body message 
{
  "code": "missing_parameter",
  "message": "Required parameter is missing.",
  "data": {
    "name": "amount"
  }
}
. 
So please help me as early as possible to get proper output. Is anything is missing from .cfg file?

**Comment by bartekn** [comment]
This doesn't seem to be an issue with a bridge server. I can see that you have already asked this at [Stack Exchange](https://stellar.stackexchange.com/questions/749/payment-not-send-by-bridge-server) which is a better place to ask questions. Closing.
