### ISSUE TITLE
how to connect bridge-server to my own configured stellar-core

### ISSUE THREAD

**Issue by AnkitRathore175** [stellar/bridge-server#118]
Hello Guys,
I need to connect the bridge-server to my owned configured private stellar-code node, which is currently running on HTTP_PORT=11626
I tried to put the local path like "127.0.0.1:11626" and "localhost:11626" in bridge.cfg into the horizon option.
Thanks

**Comment by bartekn** [comment]
Bridge does not connect to `stellar-core` directly. Please ask questions at [Stack Exchange](https://stellar.stackexchange.com).
