### ISSUE TITLE
FATA[0000] Cannot connect to a DB: dial tcp 127.0.0.1:3306: getsockopt: connection refused

### ISSUE THREAD

**Issue by hikame** [stellar/bridge-server#120]
I created the bridge.cfg file exactly same as https://github.com/stellar/bridge-server/blob/master/bridge_example.cfg and run "./bridge --migrate-db" as written in readme_bridge.md.
However, I got an error:

FATA[0000] Cannot connect to a DB: dial tcp 127.0.0.1:3306: getsockopt: connection refused

It seems that my mysql database could not be connected.
How can I fix it?

**Comment by bartekn** [comment]
Check if MySQL is listening on `3306` port. For more help please ask your questions at [Stellar Stack Exchange](http://stellar.stackexchange.com).
