### ISSUE TITLE
Generic Create TX endpoint

### ISSUE THREAD

**Issue by jedmccaleb** [stellar/bridge-server#13]
Should we add an endpoint that builds txs for them maybe from some json object or something?
This would allow people to do arbitrary txs without having a lib to build the XDR.

Something like:
```
{
   ops: [
      { 
       type: allow_trust,
       issuer: GBEZOC5U4TVH7ZY5N3FLYHTCZSI6VFGTULG7PBITLF5ZEBPJXFT46YZM,
       asset_code: "BTC"
      },
      {
         type: set_options,
         inflation_dest: GBEZOC5U4TVH7ZY5N3FLYHTCZSI6VFGTULG7PBITLF5ZEBPJXFT46YZM
      }       
    ]
```

An alternative would be an endpoint that will do the change trust operation since other than payment this is probably the most common. 

@nullstyle I bet you have thoughts here.

**Comment by nullstyle** [comment]
I think it makes sense... Adding it to the bridge server is a good compromise between my proposal last year to add this capability to horizon and nico's concern about trusting the transaction that the software creates.

If I were designing the server I would try to mirror the response output of horizon for the input to this server.  Specifying an operation in this service should have the same general shape as the operation resource in horizon.

**Comment by bartekn** [comment]
Work in progress: https://github.com/stellar/bridge-server/compare/master...transaction-builder
