### ISSUE TITLE
`source` parameter for payments does not fall back to `base_seed` from configuration

### ISSUE THREAD

**Issue by Mr0grog** [stellar/bridge-server#28]
The docs suggest that the `base_seed` configuration parameter will be used to determine the transaction source for payments, but the `source` param is still required anyway (https://github.com/stellar/bridge-server/blob/0.0.12/src/github.com/stellar/gateway/protocols/bridge/payment.go#L63) and there certainly doesn't appear to be any code for the fallback anyway (https://github.com/stellar/bridge-server/blob/0.0.12/src/github.com/stellar/gateway/protocols/bridge/payment.go#L128)

As a side note: what is the point of that config param if this doesn't work?

**Comment by jedmccaleb** [comment]
That is a bug. `source` shouldn't be required.
