### ISSUE TITLE
Allow to specify config file names

### ISSUE THREAD

**Issue by 31z4** [stellar/bridge-server#45]
Having `--conf` in both `bridge` and `compliance` for that would be great!

**Comment by ramontayag** [comment]
I've been exploring a way to deploy on docker and having a templating script that, reading environment variables, generates a config file in the right place seems like the hard way to do it. The simplest might be to mount a disk onto the container, with the config file uploaded, and pointing to it: `bridge -c /mnt/mydisk/config.toml`
