### ISSUE TITLE
[Bridge] Watching multiple accounts

### ISSUE THREAD

**Issue by ramontayag** [stellar/bridge-server#53]
I'm looking to build an app that will watch multiple addresses, without knowing them ahead of time. It looks like my option today is to subscribe to the stream straight from my app. Since bridge already does this but for one address at a time, perhaps the addresses being watched can be database-driven so multiple ones can be created.

- This table can be called "address_observers" or something like that.
- An address observer has, at least, an `address` field
- if a receiving address is specified in the cfg file, an entry is created in the db (for backward compatibility)

Does this sound like a feature that fits the scope of the bridge server?

**Comment by jedmccaleb** [comment]
Hmm that is a bit of a stretch for what the bridge is supposed to do I think. You can of course just ask horizon to listen to several accounts

**Comment by ramontayag** [comment]
Alright thanks @jedmccaleb!

**Comment by bartekn** [comment]
@irisli built a tool that does exactly what you described: https://github.com/irisli/stellar-lookout

**Comment by ramontayag** [comment]
Thanks @bartekn. I'll check it out.

**Comment by ramontayag** [comment]
It looks like what I was thinking of building, but on Ruby.
