### ISSUE TITLE
Allow listening for XLM

### ISSUE THREAD

**Issue by bartekn** [stellar/bridge-server#56]

**Comment by sacarlson** [comment]
Yes this is what I need.  can't be much trouble to add?  if I see no progress here in a few days I'll attempt making the needed change myself in my own branch.  However I suck at Go but that's not all I suck at most of you should know ha ha. as far as configs I'm thinking:  [[assets]]  code = "native"

**Comment by sacarlson** [comment]
I was able to get it working with small change to payment_listener.go
added 3 lines

if asset.Code == "native" && len(code) == 0 && len(issuer) == 0 {
	return true
}

https://github.com/stellar/bridge-server/blob/master/src/github.com/stellar/gateway/listener/payment_listener.go#L268

now looks like:
func (pl *PaymentListener) isAssetAllowed(code string, issuer string) bool {
	for _, asset := range pl.config.Assets {
		if asset.Code == code && asset.Issuer == issuer {
			return true
		}
                if asset.Code == "native" && len(code) == 0 && len(issuer) == 0 {
			return true
		}
	}
	return false
}


with this you can now add native in config

[[assets]]
code="native"

**Comment by bartekn** [comment]
Closed in https://github.com/stellar/bridge-server/pull/65
