### ISSUE TITLE
Add uniqueID to /payment

### ISSUE THREAD

**Issue by jedmccaleb** [stellar/bridge-server#58]
This will fix the case where they call /payment but never hear back. They don't know if they should re-post or if the tx was sent.

uniqueID should just be an opaque string.

**Comment by bartekn** [comment]
We should probably modify `/payment` like this:
* If `payment_id` not set, work as before.
* If `payment_id` set:
  * Check if `payment_id` already saved, if so, load transaction XDR from a DB and submit to Horizon.
  * For new `payment_id`, when tx is built, save `payment_id => transaction XDR` mapping in a DB and continue as before.

**Comment by poliha** [comment]
Makes sense, do we create a new DB table for this or use existing one and extend it?

**Comment by bartekn** [comment]
Let's create a new table.
