### ISSUE TITLE
print version

### ISSUE THREAD

**Issue by tempofr** [stellar/bridge-server#64]
It would be nice if bridge and compliance server printed their version if you run 

./bridge -V

**Comment by bartekn** [comment]
Closed by #69 and #77.

**Comment by tempofr** [comment]
stellar_auth@blue:~/bridge-v0.0.27/bin$ ./bridge -c ../bridge.cfg  --version
Bridge Server Version: N/A 
Works - but maybe some static data is missing? 
Thanks
