### ISSUE TITLE
Pass back field validation errors to sender on compliance server

### ISSUE THREAD

**Issue by tempofr** [stellar/bridge-server#70]
Currently it appears that the compliance server can return several responses on the sanctions check.

- 200 - ok
- 202 - delayed
- 403 - denied

We need the ability to pass back validation errors. For example if the country code is not iso2, or birthdate is not iso format. This could be 400 + text or maybe 422 as per this discussion. https://stackoverflow.com/questions/3290182/rest-http-status-codes-for-failed-validation-or-invalid-duplicate

**Comment by jedmccaleb** [comment]
First add change to SEP

**Comment by bartekn** [comment]
Closed in https://github.com/stellar/bridge-server/pull/82
