### ISSUE TITLE
Cannot start bridge configuraiton

### ISSUE THREAD

**Issue by agomez314** [stellar/bridge-server#85]
Typing `./bridge --migrate-db` returns `-bash: ./bridge: No such file or directory`. I have created a table, `stellar_bridge`, in mysql, added the bridge.cfg file as shown in the documentation and have successfully compiled the bridge server. I don't know why it's throwing me this error.

Also, when I start `godoc -goroot=. -http=:6060` I am able to go to the url successfully but the console throws this error:
```
2017/12/10 07:02:10 updateMetadata: open doc: no such file or directory
2017/12/10 07:02:10 updateMetadata: open doc: no such file or directory
```

Would kindly like your help, I am very excited to start building on the Stellar platform. Thank you.

**Comment by bartekn** [comment]
Do you have `bridge` binary in the working directory?
