### ISSUE TITLE
Configure Bridge Server 

### ISSUE THREAD

**Issue by safeerk** [stellar/bridge-server#96]
![image](https://user-images.githubusercontent.com/22815639/36351438-d172a54e-14ba-11e8-9381-c37b4a3f5411.png)

Hi, When i try to configure Bridge server am getting response like this.
Attaching config file also: (Below)
[bridge - Copy.txt](https://github.com/stellar/bridge-server/files/1734656/bridge.-.Copy.txt)

**Comment by khadar439** [comment]
hi If you haven't install first install it and then create database 'stellar_bridge'
then follow the below image
![bridge_cnf](https://user-images.githubusercontent.com/33127340/36644510-8ba74106-1a81-11e8-8359-ad002ce013a0.png)

**Comment by safeerk** [comment]
Thanks khader, i have already tried the above .. am having some config file issue.... Am putting the config file DB connection part below.. Kindly help me on it.

[database]
type = "mysql"
url = "root:123456@(host:3301)/stellar_bridge"

Username: root
password: 123456
MySQL Port: 3301 (not 3306)
DB :  stellar_bridge

             I dont know where i can give the IP or Localhost here... I think the format specified is wrong.

**Comment by safeerk** [comment]
Thanks i got... 
Solution:
url = "root:123456@tcp(localhost:3301)/stellar_bridge"
