### ISSUE TITLE
Bridge Server Config for MYSQL

### ISSUE THREAD

**Issue by safeerk** [stellar/bridge-server#99]
HI, Below the is the Config for Bridge server which has been provided , can you please let me know the format is correct.

MYSQL Username: root
Mysql password: 123456
Mysql port: 3301
MySQL DB: stellar_bridge

`[database]
type = "mysql"
url = "root:123456@(host:3301)/stellar_bridge"`

I dont know where i can give the IP or 127.0.0.1 on the config..
After this i need to migrate the bridge DB sttructure... Looking for guidance on this.

Regards
S

**Comment by bartekn** [comment]
There's a link to MySQL connection URI format in the "Config" section in the Bridge Server README file: https://github.com/go-sql-driver/mysql#dsn-data-source-name
